#!/bin/bash


rofi_command="rofi -theme $HOME/.config/polybar/scripts/themes/batinfo.rasi"

#uptime=$(uptime -p | sed -e 's/up //g')

# Options
#shutdown=" Shutdown"
#reboot=" Restart"
#lock=" Lock"
#suspend=" Sleep"
#logout=" Logout"

# Variable passed to rofi
#options="$logout\n$reboot\n$shutdown"
options=$(acpi | cut -d ',' -f2)
chosen="$(echo -e "$options" | $rofi_command -p "Bateria" -dmenu -selected-row 0)"
#case $chosen in
#    $shutdown)
#        poweroff
#        ;;
#    $reboot)
#        reboot
#        ;;
#    $logout)
#        pkill -KILL -u jordi
#        ;;
#esac

